SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
JOIN ITEM_TREE T ON I.ITEM_ID = T.ITEM_ID
WHERE T.PARENT_ITEM_ID IN (SELECT I.ITEM_ID
                           FROM ITEM_INFO I
                           WHERE I.RARITY = 'RARE')
ORDER BY I.ITEM_ID DESC;